[package]
name = "seagulla-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
seagulla-core = { path = "../seagulla-core" }
seagulla-db = { path = "../seagulla-db" }
seagulla-ingest = { path = "../seagulla-ingest" }
seagulla-search = { path = "../seagulla-search" }
